server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    profile: dev
    label: master
    discovery:
      enabled: true
      service-id: app-service,app2-service
    gateway:
      discovery.locator:
        enabled: true
      routes:
      - id: app1
        uri: lb://app-service
        predicates:
         - Path=/app1/**
        filters:
        - StripPrefix=1
      - id: app2
        uri: lb://app2-service
        predicates:
         - Path=/app2/**
        filters:
        - StripPrefix=1


# erueka service registe
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

    