server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    profile: dev
    #对应config server中配置文件的{label}
    label: master
    discovery:
      #表示使用服务发现组件中提供的Config Server，默认是false
      #开启通过服务发现组件访问Config Server的功能
      enabled: true
      #指定Config Server在服务发现组件中的serviceId 默认是configserver
      service-id: 'app-service,app2-service'
    gateway:
      discovery.locator:
        enabled: true
      routes:
      - id: app1
        # uri: http://example.org
        uri: lb://app-service
        predicates:
         - Path=/app1/**
        filters:
        - StripPrefix=1
      - id: app2
        # uri: http://example.org
        uri: lb://app2-service
        predicates:
         - Path=/app2/**
        filters:
        - StripPrefix=1

    